config/routes.rb
Rails.application.routes.draw do
  get 'welcome', to: 'welcome#index'
  get "welcome", to: "welcome#show", as: "new_log_in"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/sessions/new", to: "sessions#new", as: "new_session"
  post "/sessions", to: "sessions#create", as: "sessions"
  get "/sessions", to: "sessions#show", as: "log_in"
  delete "/sessions", to: "sessions#destroy"

  resources :articles
  resources :users
  resources :likes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :users, through: :likes

  has_many :likes

  validates :title, presence: true
  validates :content, length: { minimum: 50 }
  validates :content, presence: true 
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :user_id, uniqueness: { scope: [:article_id] }
  validates :article_id, uniqueness: { scope: [:user_id] }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles

  has_many :likes, through: :articles

  validates :username, uniqueness: true
  validates :username, presence: true
  validates :username, length: { maximum: 15 }
  validates :age, numericality: { greater_than: 16 }
  validates :bio, length: { maximum: 150 } 
  validates :bio, presence: true 
  validates :password, length: {minimum: 6 }
  validates :password, presence: true

  def most_liked_article
    current_highest_article = nil
    current_likes = 0
    self.articles.each do |article|
      if article.likes.count > current_likes
        current_highest_article = article
        current_likes = article.likes
      end
    end
    current_highest_article
  end
  # def featured_article
  #   self.articles.max_by {|article| article.likes}
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
    
  def current_user
    if session[:user_id]
        User.find(session[:user_id])
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end
    
  def create 
    @article = Article.new(strong_boy_params)
    @article.user = current_user
    @article.save
    if @article.valid?
      @article.save 
      redirect_to article_path(@article)
    else
      render :new
    end
  end
    
  def index 
    @articles = Article.all
  end
    
  def show
    set_article
    @user = current_user
    # byebug
  end
    
  def edit 
    set_article

  end
    
  def update
    @article = Article.find(params[:id])
    @article.update(strong_boy_params)
    flash[:notice] = "Your Article Was Updated"
    redirect_to article_path(@article)
  end
    
  def destroy
    set_article
    @article.destroy 
    redirect_to articles_path
  end
    
  def like 
    set_article 
    @article.destroy
    flash[:notice] = "Article Was Deleted"
    redirect_to article_path(@article)
  end

  def set_article 
    @article = Article.find(params[:id])
  end
    
    private
  def strong_boy_params
    params.require(:article).permit(:title, :content, :user_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def new
    @like = Like.new
  end

  def create 
    @like = Like.new(strong_like_params)
    if @like.valid?
    @like.save
    redirect_to new_like_path
    end
  end
  
  def show 
    @like = Like.find(params[:id])
    @article = Like.article_id
  end
  
  private 

  def strong_like_params
    params.require(:like).permit(:user_id, :article_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
 
  def create
    @user = User.find_by(username: params[:user][:username])
    if @user
      session[:user_id] = @user.id 
      redirect_to log_in_path
    else
      
      redirect_to new_session_path, :notice => "Sorry, But We Can't Find A Member With That Username Or Password"
    end
  end

  def destroy
    session.destroy
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
    
  def new
    @user = User.new
  end
    
  def create 
    @user = User.new(strong_boy_user_params)
    if @user.valid?
      @user.save
      flash[:success] = "Welcome to the BLOGBUSTERS #{@user.username}"
      redirect_to new_log_in_path
    else
      render :new
    end
  end
      
  def show 
    set_user
  end
    
  def destroy 
    set_user
    session.destroy
    @user.destroy 
    redirect_to users_path
  end

  def set_user
    @user = User.find(params[:id])
  end
    
  private
      
  def strong_boy_user_params
    params.require(:user).permit(:username, :password, :age, :bio)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1 align="center">EDIT MY ARTICLE!</h1>
<% if @article.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(@article.errors.count, "error") %>
      prohibited this Edit from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% @article.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :title %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :content %>
   </div>
   <div class="col-sm-6">
    <%= f.text_area :content, rows: 10, class: "form-control", placeholder: "Body of article" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-large' %>
   </div>
  </div>
<% end %>
 </div>
</div>

app/views/articles/index.html.erb
 

<h1 align="center">Listing all articles</h1>
<% @articles.each do |article| %>
<br><br>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="well well-lg">
    <div class="article-title">
     <%= link_to article.title, article_path(article) %>
     </div>
    <div class="article-body">
     <%= truncate(article.content, length: 100) %>
    </div>
 
    <div class="article-actions">
    
     
    </div>
   </div>
  </div>
 </div>

<% end %>

app/views/articles/new.html.erb
<h1 align="center">NEW ARTICLE</h1>
<% if @article.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(@article.errors.count, "error") %>
      prohibited this article from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% @article.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :title %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :content %>
   </div>
   <div class="col-sm-6">
    <%= f.text_area :content, rows: 10, class: "form-control", placeholder: "Body of article" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-5 col-sm-5">
    <%= f.submit class: 'btn btn-success btn-large' %>
   </div>
  </div>
<% end %>
 </div>
</div>
<h2 align="center"><%= link_to  "Actually i've changed my mind and i have nothing important to say at all...", articles_path, class: 'btn btn-success btn-large' %></h2>

app/views/articles/show.html.erb
<h2 align="center"> <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
 <h4 class="center"><strong>Author: <%=@article.user.username %></strong></h4>
 <hr>
 <%= simple_format(@article.content) %>
<%= link_to 'Back', articles_path, class: "btn btn-xs btn-success" %>

<%= link_to 'Like', new_like_path(:like => {:user_id => current_user.id, :article_id => @article.id}), class: "btn btn-xs btn-info" %>

<% if @user.id == @article.user_id %>

<%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
<%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar nnavbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "BLOGBUSTERS", welcome_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <% if current_user %>
        <li><%= link_to "Members", users_path %>
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Create Article", new_article_path %></li>
        <% end %>
          </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
      <p class="navbar-text", style="color:MediumSeaGreen;">Signed in as <%= current_user.username %></p>
      <button type="button" class="btn btn-warning navbar-btn"><%= link_to "Log Out", sessions_path, method: :delete %> </button>
      <% else %>
      <button type="button" class="btn btn-success navbar-btn"><%= link_to "Sign in", new_session_path %> </button>
      <button type="button" class="btn btn-warning navbar-btn"><%= link_to "Sign Up", new_user_path %> </button>
      <% end %>
        
        
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BLOGBUSTERS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>

      
   
    <%= yield %>
 
     
  </body>
</html>

app/views/likes/new.html.erb
<h1 align="center"><%=current_user.username%> You've Liked This article!</h1>
<br>
<h2 align="center"><%= link_to "Go Back", article_path(params[:like][:article_id]), class: "btn btn-lg btn-success" %></h2>
<div class="frontlogo", align="center"><%= image_tag  "logo.jpeg" %></div>

app/views/users/index.html.erb
<h1 align="center">YOUR FELLOW BLOGBUSTERS (A List Of Really Cool People!)</h1>
<br>
<% @users.each do |user| %>

<br>
<div class="row">
  <div class="col-xs-4 col-xs-offset-4">
   <div class="well well-sm">
    <div class="user-username">
     <h1 align="center"><%= link_to user.username, user_path(user), class: 'btn btn-success btn-lg btn-block' %></h1>
     </div>
    <div class="user-actions">
    </div>
   </div>
  </div>
 </div>

<% end %>

  

app/views/users/new.html.erb
<h1 align="center"> SIGN UP </h1>
<% if @user.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being created:
     </h2>
     <div class="panel-body">
      <ul>
       <% @user.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
 <% end %>
 <br><br>
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-4">
    <%= f.label :username %>
   </div>
   <div class="col-sm-4">
    <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-4">
    <%= f.label :age %>
   </div>
   <div class="col-sm-4">
    <%= f.number_field :age, class: "form-control", placeholder: "How Old Are You?" %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-4">
    <%= f.label :bio %>
    </div>
   <div class="col-sm-4">
    <%= f.text_field :bio, class: "form-control", placeholder: "Tell Us About Yourself" %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-4">
   <%= f.label :password %>
   </div>
   <div class="col-sm-4">
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
   </div>
  </div>  
  <div class="form-group">
   <br><br>
   <h5 align="center"><%= f.submit class: "btn btn-success btn-large" %></h5>
   </div>
  </div>
  <br><br>
  <br><br>
  <br><br>
<h2 align="center"><%= link_to "Actually, I Changed My Mind, I Don't Want To Join This Exclusive Club...", welcome_path, class: "btn btn-success btn-large" %></h2>
<% end %> 

app/views/users/show.html.erb
<h1 align="center"> BLOGBUSTER MEMBER </h1>
<br><br>
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<br><br>
<h2 align="center"><%= @user.age %></h2>
<br><br>
<h2 align="center"><%= @user.bio %></h2>
<br><br>
<h2 align="center"><%= @user.username %>'s Most Liked Article!</h2>
<% if @user.articles.length > 0 %>
<br><br>
<h2 align="center"><%= link_to @user.most_liked_article.title, article_path(params[:id]), class: "btn btn-lg btn-success" %></h2>
<% else %>
<br><br>
<h3 align="center"><%=@user.username%> Doesn't Have Any Likes Yet... GO SHOW THEM SOME LOVE!!!</h3>
<% end %>
<br><br>
<% if current_user.id == @user.id %>
<h1 align="center"><%= link_to "Delete My Account", user_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete your Account?"}, class: "btn btn-lg btn-danger" %></h1>
 <% end %>

app/views/welcome/index.html.erb
<h1 align="center">WELCOME TO BLOGBUSTERS</h1>
<br>
<h2 align="center"> A PLACE TO WRITE, VIEW AND LIKE SOME OF THE BEST ARTICLES AROUND! </h2> 
<div class="frontlogo", align="center"><%= image_tag  "logo.jpeg" %></div>

app/views/welcome/newuser.html.erb
<h1 align="center"><%= "Welcome to the BLOGBUSTERS #{@user.username}"%></h1>
<div class="frontlogo", align="center"><%= image_tag  "logo.jpeg" %></div>